import ExpoConstants from "expo-constants";
const env = ExpoConstants.manifest.extra.env;
export interface IConstants {
  FIREBASE_API_KEY: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
  FIREBASE_MESSAGING_SENDERID: string;
  FIREBASE_APP_ID: string;
  FIREBASE_MEASUREMENT_ID: string;
  FIREBASE_DATABASE_URL: string;
  AUTH_APP_ID: string;
  AUTH_APP_SECRET: string;
  AUTH_DISCOVERY_URL: string;
  BACKEND_BASE_URL: string;
}

export const Constants: IConstants = {
  FIREBASE_API_KEY: env?.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: env?.FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: env?.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: env?.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDERID: env?.FIREBASE_MESSAGING_SENDERID,
  FIREBASE_APP_ID: env?.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: env?.FIREBASE_MEASUREMENT_ID,
  FIREBASE_DATABASE_URL: env?.FIREBASE_DATABASE_URL,
  AUTH_APP_ID: env?.AUTH_APP_ID,
  AUTH_APP_SECRET: env?.AUTH_APP_SECRET,
  AUTH_DISCOVERY_URL: env?.AUTH_DISCOVERY_URL,
  BACKEND_BASE_URL: env?.BACKEND_BASE_URL,
};
